name: Release & Publish
on:
  workflow_call:
    inputs:
      version_type:
        type: string
        description: "Version type"
        required: false
      release_channel:
        type: string
        description: "Release channel"
        required: false
      no_changelog:
        type: boolean
        description: "Generate changelog"
        required: false
        default: true

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Pull changes
        run: git pull
      - name: Automated Version Bump
        id: version_bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: ${{ github.event.inputs.version_type }}
          skip-tag: true
    outputs:
      newTag: ${{ steps.version_bump.outputs.newTag }}

  changelog:
    if: ${{ !github.event.inputs.no_changelog }}
    needs: bump
    uses: maicol07/actions/.github/workflows/changelog.yml@main
    with:
      next_version: ${{ needs.bump.outputs.newTag }}
      config_dir: ${{ github.event.inputs.config_dir }}
      filename: ${{ github.event.inputs.filename }}
      path: ${{ github.event.inputs.path }}
      tag_query: ${{ github.event.inputs.tag_query }}
      commit_message: ${{ github.event.inputs.commit_message }}

  release:
    runs-on: ubuntu-latest
    needs: [bump, changelog]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Pull changes
        run: git pull
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ needs.bump.outputs.newTag }}
          tag_exists_error: true
          message: "Release ${{ needs.bump.outputs.newTag }}"
          commit_sha: ${{ needs.changelog.outputs.commit_sha }}
      - name: Generate changelog only for the newest tag
        id: new_tag_changelog
        uses: maicol07/github-changelog-action@master
        with:
          tag_query: ${{ needs.bump.outputs.newTag }}
          filename: CHANGELOG-release.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG-release.md
          tag_name: ${{ needs.bump.outputs.newTag }}
      - name: Remove File
        run: rm CHANGELOG-release.md

  publish:
    runs-on: ubuntu-latest
    needs: [bump, changelog, release]
    strategy:
      matrix:
        node-version: [19]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Pull changes
        run: git pull
      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish
        run: pnpm publish --access public --tag ${{ github.event.inputs.release_channel }}
