name: Release & Publish
on:
  workflow_call:
    inputs:
      version_type:
        type: string
        description: "Version type"
        required: false
      release_channel:
        type: string
        description: "Release channel"
        required: false

jobs:
  release_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Pull changes
        run: git pull

      - name: Automated Version Bump
        id: version_bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: ${{ github.event.inputs.version_type }}

      - name: Generate changelog only for the newest tag
        id: new_tag_changelog
        uses: maicol07/github-changelog-action@master
        with:
          tag_query: ${{ steps.version_bump.outputs.newTag }}
          filename: CHANGELOG-release.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG-release.md
          tag_name: ${{ steps.version_bump.outputs.newTag }}
      - name: Remove File
        run: rm CHANGELOG-release.md
      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish
        run: pnpm publish --access public --tag ${{ github.event.inputs.release_channel }}
