name: Release & Publish
on:
  workflow_call:
    inputs:
      config_dir:
        description: '[CHANGELOG] git-chglog configuration directory'
        type: string
        default: '.chglog'
        required: false

      filename:
        description: '[CHANGELOG] Filename to write the changelog to'
        type: string
        required: false
        default: CHANGELOG.md

      path:
        description: '[CHANGELOG] Optional path to follow for directory'
        default: ''
        type: string
        required: false

      tag_query:
        description: '[CHANGELOG] Optional tag query to use for changelog generation'
        default: ''
        type: string
        required: false

      commit_message:
        type: string
        description: "[CHANGELOG] Commit message"
        required: false

      version_type:
        type: string
        description: "Version bump type"
        required: false

      release_channel:
        type: string
        description: "Release channel"
        required: false

jobs:
  # Shrink the workflow to only one job
  release_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Pull changes
        run: git pull
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      # Bump & Changelog
      - name: Automated Version Bump
        id: version_bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: ${{ github.event.inputs.version_type }}
          skip-tag: true
          skip-push: true
      - name: Generate changelog
        id: changelog
        uses: maicol07/github-changelog-action@master
        with:
          next_version: ${{ steps.version_bump.outputs.newTag }}
          config_dir: ${{ github.event.inputs.config_dir }}
          filename: ${{ github.event.inputs.filename }}
          path: ${{ github.event.inputs.path }}
          tag_query: ${{ github.event.inputs.tag_query }}
          commit_message: ${{ github.event.inputs.commit_message }}
#      - name: Commit changes
#        uses: EndBug/add-and-commit@v7
#        with:
#          message: ${{ github.event.inputs.commit_message }}
#          add: ${{ github.event.inputs.filename }}
      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        id: git_auto_commit
        if: ${{ !github.event.inputs.commit_message }}
        with:
          commit_message: "changelog: 📝 Updated changelog for release ${{ steps.version_bump.outputs.newTag }}"
          file_pattern: 'CHANGELOG.md'

      # Release
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ steps.version_bump.outputs.newTag }}
          tag_exists_error: true
          message: "Release ${{ steps.version_bump.outputs.newTag }}"
          commit_sha: ${{ steps.git_auto_commit.outputs.commit_hash }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Generate changelog only for the newest tag
        id: new_tag_changelog
        uses: maicol07/github-changelog-action@master
        with:
          tag_query: ${{ steps.version_bump.outputs.newTag }}
          filename: CHANGELOG-release.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG-release.md
          tag_name: ${{ steps.version_bump.outputs.newTag }}
      - name: Remove File
        run: rm CHANGELOG-release.md

      # Publish to NPM
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

#      - name: Pull changes
#        run: git pull
      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish
        run: pnpm publish --access public --tag ${{ github.event.inputs.release_channel }}
