name: Release & Publish
on:
  workflow_call:
    inputs:
      release_channel:
        default: "latest"
        type: string
        description: "Release channel"
      release_type:
        type: string
        description: "Release type"
        required: false
        default: "node"
      pnpm_version:
        type: string
        description: "PNPM version"
        required: false
        default: latest


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: ${{ inputs.release_type }}
          pull-request-title-pattern: 'chore: release ${version}'
    outputs:
        release_created: ${{ steps.release.outputs.release_created }}

  publish:
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.release_created
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ inputs.pnpm_version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish
        run: pnpm publish --access public ${{ inputs.release_channel && '--tag' || '' }} ${{ inputs.release_channel || '' }}
